version: '3'

services:
  app:
    build: .
    container_name: app
    #entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    #environment:
      # - DB_HOST=db
       #- DB_DATABASE=laravel
       #- DB_USERNAME=root
       #- DB_PASSWORD=root
    security_opt:
      - apparmor:docker-default
    volumes:
      - .:/var/www
    networks:
       - app-networks
    depends_on:
       - db
       - redis
  nginx:
    build: .docker/nginx
    container_name: 'nginx'
    security_opt:
      - apparmor:docker-default
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-networks
    depends_on:
      - app
  db:
    image: mysql:5.7
    container_name: db
    security_opt:
      - apparmor:docker-default
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-networks
  redis:
    image: redis:alpine
    security_opt:
      - apparmor:docker-default
    expose:
      - 6379
    networks:
      - app-networks
networks:
  app-networks:
    driver: bridge
